fix stats layout and add tooltips
DevLeonardoCommunity/github-stats pull request #101
Opened 2024-01-29 09:35 UTC by theflucs

Fix responsive card layout
Add tooltips to pr and contribution title (removed title tag)

2024-01-29 09:46 UTC, theflucs commented on src/components/RepositoryContributionsCard.tsx
> +                  data-tip={title}
This is a workaround for correctly displaying the tooltips.
If it is set to` tooltip-top` the first item's tooltip doesn't show, as well as if it is set to  `tooltip-bottom` the last one doesn't appear either. Feel free to discard these lines if you know a cleaner way to achieve the correct displaying of the tooltips.

2024-01-29 19:33 UTC, Balastrong requested changes

2024-01-29 19:33 UTC, Balastrong commented on src/components/RepositoryContributionsCard.tsx
> +                { pullRequest: { state, title, id, url } }: any,
We should probably add a better type here than `any`, I think there's already a type in `types/github.ts` for that

2024-01-29 21:34 UTC, CBID2 requested changes
For the most part, it looks good, but I do see some of the long titles not be in-line (see the card that says "Accessible For All" for reference in the below screenshot) 
![test for tooltip contribution](https://github.com/DevLeonardoCommunity/github-stats/assets/105683440/8525bc3a-ccc1-4b7f-84b3-eefba920c03f).

Is there a way you can make the tooltip work for all long titled-PRs @theflucs? :) What do you think @Balastrong?

2024-01-30 08:21 UTC, theflucs commented on src/components/RepositoryContributionsCard.tsx
> +                  data-tip={title}
Ouch, I didn't notice it. And it makes sense it doesn't work. We need to find another way :thinking:
@CBID2 you can take over this if you like

2024-01-30 08:28 UTC, theflucs commented
@CBID2 are you sure your code is aligned with this branch? The PR title shows the 3 dots, if too long, and also the contribution icons should be aligned with the PR title pill, they don't look like. The tooltip part I think is fixed for the PR title but not for the contribution title, as mentioned above by @Balastrong

2024-01-30 12:42 UTC, CBID2 commented
> @CBID2 are you sure your code is aligned with this branch? The PR title shows the 3 dots, if too long, and also the contribution icons on the right should be aligned with the PR title pill, they don't look like. The tooltip part I think is fixed for the PR title but not for the contribution title, as mentioned above by @Balastrong. You can have a look at it and see if you come up with a solution

@Balastrong this deployment needs approval again.

2024-01-30 14:23 UTC, Balastrong commented
@CBID2 the deploy is not working at the moment, it redirects to an old version.

In order to test this branch you should checkout it locally and run the app there :)

2024-01-31 08:54 UTC, Balastrong approved these changes
Overall it looks good to me as the scope of the PR was only on PR titles actually, I'd go with merging it so we keep small changes.

@CBID2 thanks for the review! If you find something else that needs to be tweaked feel free to create new issues so we can start from there!

2024-01-31 08:56 UTC, merged

2024-01-31 10:12 UTC, CBID2 commented
> @all-contributors please add @CBID2 for review

@Balastrong, you used my name instead of @theflucs. Did you mean to do that?

2024-01-31 10:51 UTC, Balastrong commented
Yes, I added you for the review :D